// src/pages/dashboard/pages/_components/AddPageForm.svelte
<script lang="ts">
import { addPage } from "@pages/dashboard/_stores/dashboardStore.svelte";

let addPageForm: HTMLFormElement;
let addPageFormTitleInput: HTMLInputElement;

async function submit(event: SubmitEvent) {
    event.preventDefault();

    const formData = new FormData(event.currentTarget as HTMLFormElement);
    const response = await fetch("/api/v1/pages", {
        method: "POST",
        body: formData,
    });
    const data = await response.json();

    addPage(data);

    addPageForm.reset();
    addPageFormTitleInput.focus();
}
</script>

<form bind:this={addPageForm} onsubmit={submit}>
    <div>
        <label for="page-title">Title</label>
        <input
            bind:this={addPageFormTitleInput}
            type="text"
            id="page-title"
            name="title"
        />
    </div>
    <div>
        <label for="page-url">Url</label>
        <input type="text" id="page-url" name="url" />
    </div>
    <div>
        <button>Add page</button>
    </div>
</form>

// src/pages/dashboard/pages/_components/AddPageForm.vue
<template>
    <form ref="add-page-form" @submit.prevent="addPage">
        <div>
            <label for="page-title">Title</label>
            <input
                ref="add-page-form-title-input"
                type="text"
                id="page-title"
                name="title"
            />
        </div>
        <div>
            <label for="page-url">Url</label>
            <input type="text" id="page-url" name="url" />
        </div>
        <div>
            <button type="submit">Add page</button>
        </div>
    </form>
</template>

<script setup lang="ts">
import { useTemplateRef } from "vue";
import { useDashboardStore } from "@pages/dashboard/_stores/dashboardStore";

const store = useDashboardStore();
const addPageForm = useTemplateRef("add-page-form");
const addPageFormTitleInput = useTemplateRef("add-page-form-title-input");

async function addPage(event) {
    const formData = new FormData(event.currentTarget as HTMLFormElement);
    const response = await fetch("/api/v1/pages", {
        method: "POST",
        body: formData,
    });
    const data = await response.json();

    store.addPage(data);

    addPageForm.value.reset();
    addPageFormTitleInput.value.focus();
}
</script>
